Add support for "eslint-plugin-qunit"
simplabs/eslint-config-simplabs pull request #9
Opened 2017-02-01 17:44 UTC by Turbo87

Similar to #8 but using https://github.com/platinumazure/eslint-plugin-qunit

2017-02-01 17:49 UTC, gr0uch requested changes

2017-02-01 17:49 UTC, sapeien commented on node-tests/blueprints/eslint-config-simplabs-test.js
> +          .to.equal(`module.exports = {\n  extends: [\n    'simplabs/configs/ember-qunit',\n    'simplabs/rules/qunit',\n  ],\n};\n`);
Fixture file maybe?

2017-02-01 18:30 UTC, marcoow commented on blueprints/eslint-config-simplabs/files/tests/.eslintrc.js
>  <% } else { %>
Should this be `} else if (hasEmberCLIQUnit) {`?

2017-02-01 18:43 UTC, marcoow reviewed
let's discuss linting rules again 🙌

2017-02-01 18:43 UTC, marcoow commented on blueprints/eslint-config-simplabs/files/tests/.eslintrc.js
>  <% } else { %>
Should this be `} else if (hasEmberCLIQUnit) {`?

2017-02-01 18:43 UTC, marcoow commented on node-tests/blueprints/eslint-config-simplabs-test.js
> +          .to.equal(`module.exports = {\n  extends: [\n    'simplabs/configs/ember-qunit',\n    'simplabs/rules/qunit',\n  ],\n};\n`);
or template string?

2017-02-01 18:43 UTC, marcoow commented on rules/qunit.js
> +    'qunit/no-early-return': 'off',
Should this be switched on? Not sure what good use cases for doing this might be.

2017-02-01 18:43 UTC, marcoow commented on rules/qunit.js
> +    'qunit/no-global-assertions': 'off',
Should this be switched on?

2017-02-01 18:43 UTC, marcoow commented on rules/qunit.js
> +    'qunit/no-global-expect': 'off',
Should this be switched on?

2017-02-01 18:43 UTC, marcoow commented on rules/qunit.js
> +    'qunit/no-global-module-test': 'off',
Should this be switched on? Not sure whether that would fire when we `import` `module` etc.?

2017-02-01 18:55 UTC, Turbo87 commented on rules/qunit.js
> +    'qunit/no-global-module-test': 'off',
Nope. The rule doesn't support destructuring `test` out of `QUnit` or importing it like `import { test } from 'qunit'`. I initially had it enabled but testing on some of our repos brought this to light. Same for the other `no-global` rules.

2017-02-01 18:55 UTC, Turbo87 commented on rules/qunit.js
> +    'qunit/no-global-expect': 'off',
see below

2017-02-01 18:55 UTC, Turbo87 commented on rules/qunit.js
> +    'qunit/no-global-assertions': 'off',
see below

2017-02-01 18:56 UTC, Turbo87 commented on rules/qunit.js
> +    'qunit/no-early-return': 'off',
I don't have a lot of experience with QUnit myself. If you think that this rule is useful I can certainly enable it.

2017-02-01 19:01 UTC, Turbo87 commented on blueprints/eslint-config-simplabs/files/tests/.eslintrc.js
>  <% } else { %>
done

2017-02-01 19:01 UTC, Turbo87 commented on rules/qunit.js
> +    'qunit/no-early-return': 'off',
done

2017-02-01 19:02 UTC, Turbo87 commented
@sapeien I changed the test code to use fixture files now

2017-02-01 21:06 UTC, marcoow commented on node-tests/blueprints/eslint-config-simplabs-test.js
> +        expect(file('tests/.eslintrc.js')).to.equal(file(`${__dirname}/fixtures/.eslintrc.qunit.js`));
Wouldn't a template string be better as we'd have the expected content right here instead of having to look it up in a separate file?

2017-02-01 21:06 UTC, marcoow commented on node-tests/blueprints/eslint-config-simplabs-test.js
> +        expect(file('tests/.eslintrc.js')).to.equal(file(`${__dirname}/fixtures/.eslintrc.mocha.js`));
Wouldn't a template string be better as we'd have the expected content right here instead of having to look it up in a separate file?

2017-02-01 21:23 UTC, Turbo87 commented on node-tests/blueprints/eslint-config-simplabs-test.js
> +        expect(file('tests/.eslintrc.js')).to.equal(file(`${__dirname}/fixtures/.eslintrc.qunit.js`));
it would be right there in the file, but it would also look very ugly due to the indentation having to be correct and everything...

2017-02-02 08:12 UTC, Turbo87 commented
merging as all the comments were addressed

2017-02-02 08:12 UTC, merged